# Generated by Django 3.1.3 on 2020-11-20 23:37

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteListPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', cpf_field.models.CPFField(max_length=14, unique=True, verbose_name='cpf')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'White List Pedido',
                'verbose_name_plural': 'White List Pedido',
                'db_table': 'white_list_pedido',
                'ordering': ['cpf'],
            },
        ),
    ]
