# Generated by Django 3.1.3 on 2020-11-18 10:55

import cpf_field.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Mínimo')),
                ('valor_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Máximo')),
                ('percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Percentual')),
            ],
            options={
                'verbose_name': 'CashBack',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=60, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Status',
            },
        ),
        migrations.AlterModelOptions(
            name='revendedor',
            options={'verbose_name': 'Revendedor', 'verbose_name_plural': 'Revendedores'},
        ),
        migrations.AlterField(
            model_name='revendedor',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, unique=True, verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='revendedor',
            name='email',
            field=models.EmailField(max_length=60, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='revendedor',
            name='nome',
            field=models.CharField(max_length=60, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='revendedor',
            name='senha',
            field=models.CharField(max_length=60, verbose_name='Senha'),
        ),
        migrations.AlterModelTable(
            name='revendedor',
            table='revendedor',
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=60, verbose_name='Número')),
                ('valor', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Valor')),
                ('data', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Pedido')),
                ('revendedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='revendedor_pedido', to='api.revendedor', verbose_name='Revendedor')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='status_pedido', to='api.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Pedido',
            },
        ),
        migrations.CreateModel(
            name='CashBackRevendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor CashBack')),
                ('data', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Pedido')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cashback_pedido', to='api.pedido', verbose_name='Pedido')),
                ('revendedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='revendedor_cashback_pedido', to='api.revendedor', verbose_name='Revendedor')),
            ],
            options={
                'verbose_name': 'CashBack Revendedor',
            },
        ),
    ]
