# Generated by Django 3.1.3 on 2020-11-18 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201118_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbackrevendedor',
            name='perc_cashback',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Perc. CashBack Aplicado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default='2020-11-18 08:10:00', verbose_name='Data/Hora Pedido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero',
            field=models.CharField(max_length=60, unique=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='status_pedido', to='api.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
    ]
