# Generated by Django 3.1.3 on 2020-11-19 19:46

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201119_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='WitheListPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', cpf_field.models.CPFField(max_length=14, unique=True, verbose_name='cpf')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Withe List Pedido',
                'verbose_name_plural': 'Withe List Pedido',
                'db_table': 'withe_list_pedido',
                'ordering': ['cpf', 'ativo'],
            },
        ),
    ]
