# Generated by Django 3.1.3 on 2020-11-17 21:09

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Revendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('cpf', cpf_field.models.CPFField(max_length=14, verbose_name='cpf')),
                ('email', models.EmailField(max_length=60)),
                ('senha', models.CharField(max_length=60)),
            ],
        ),
    ]
