# Generated by Django 3.1.3 on 2020-11-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201118_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashbackconfig',
            options={'ordering': ['percentual'], 'verbose_name': 'Config. CashBack', 'verbose_name_plural': 'Config. CashBack'},
        ),
        migrations.AlterModelOptions(
            name='cashbackrevendedor',
            options={'ordering': ['data'], 'verbose_name': 'CashBack Revendedor', 'verbose_name_plural': 'CashBack Revendedores'},
        ),
        migrations.AlterUniqueTogether(
            name='cashbackrevendedor',
            unique_together={('revendedor', 'pedido')},
        ),
        migrations.AddConstraint(
            model_name='cashbackrevendedor',
            constraint=models.CheckConstraint(check=models.Q(perc_cashback__lte=20), name='perc_cashback_lte_20'),
        ),
    ]
