# Generated by Django 3.1.3 on 2020-11-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201118_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(verbose_name='Data/Hora Pedido'),
        ),
    ]
