# Generated by Django 3.1.3 on 2020-11-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Mínimo')),
                ('valor_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Máximo')),
                ('percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Percentual')),
            ],
            options={
                'verbose_name': 'Config. CashBack',
                'verbose_name_plural': 'Config. CashBack',
                'db_table': 'cashback',
                'ordering': ['percentual'],
            },
        ),
    ]
