# Generated by Django 3.1.3 on 2020-11-20 23:37

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Revendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('cpf', cpf_field.models.CPFField(max_length=14, unique=True, verbose_name='cpf')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email')),
                ('senha', models.CharField(max_length=100, verbose_name='Senha')),
            ],
            options={
                'verbose_name': 'Revendedor',
                'verbose_name_plural': 'Revendedores',
                'db_table': 'revendedor',
                'ordering': ['nome'],
            },
        ),
    ]
