# Generated by Django 3.1.3 on 2020-11-20 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('revendedor', '0001_initial'),
        ('statuspedido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=60, unique=True, verbose_name='Número')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data', models.DateTimeField(verbose_name='Data/Hora Pedido')),
                ('revendedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='revendedor_pedido', to='revendedor.revendedor', verbose_name='Revendedor')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='status_pedido', to='statuspedido.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedido',
                'ordering': ['data'],
            },
        ),
    ]
